#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QACIglesia.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GEODB")]
	public partial class GEODBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProvincia(Provincia instance);
    partial void UpdateProvincia(Provincia instance);
    partial void DeleteProvincia(Provincia instance);
    partial void InsertMunicipio(Municipio instance);
    partial void UpdateMunicipio(Municipio instance);
    partial void DeleteMunicipio(Municipio instance);
    partial void InsertDistritoMunicipal(DistritoMunicipal instance);
    partial void UpdateDistritoMunicipal(DistritoMunicipal instance);
    partial void DeleteDistritoMunicipal(DistritoMunicipal instance);
    partial void InsertSeccion(Seccion instance);
    partial void UpdateSeccion(Seccion instance);
    partial void DeleteSeccion(Seccion instance);
    partial void InsertBarrio(Barrio instance);
    partial void UpdateBarrio(Barrio instance);
    partial void DeleteBarrio(Barrio instance);
    partial void InsertSubBarrio(SubBarrio instance);
    partial void UpdateSubBarrio(SubBarrio instance);
    partial void DeleteSubBarrio(SubBarrio instance);
    #endregion
		
		public GEODBDataContext() : 
				base(global::QACIglesia.Model.Properties.Settings.Default.GEODBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GEODBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GEODBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GEODBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GEODBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Provincia> Provincia
		{
			get
			{
				return this.GetTable<Provincia>();
			}
		}
		
		public System.Data.Linq.Table<Municipio> Municipio
		{
			get
			{
				return this.GetTable<Municipio>();
			}
		}
		
		public System.Data.Linq.Table<DistritoMunicipal> DistritoMunicipal
		{
			get
			{
				return this.GetTable<DistritoMunicipal>();
			}
		}
		
		public System.Data.Linq.Table<Seccion> Seccion
		{
			get
			{
				return this.GetTable<Seccion>();
			}
		}
		
		public System.Data.Linq.Table<Barrio> Barrio
		{
			get
			{
				return this.GetTable<Barrio>();
			}
		}
		
		public System.Data.Linq.Table<SubBarrio> SubBarrio
		{
			get
			{
				return this.GetTable<SubBarrio>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Provincia")]
	public partial class Provincia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ProvinciaId;
		
		private string _Nombre;
		
		private int _Id;
		
		private string _Region;
		
		private string _enlace;
		
		private EntitySet<Municipio> _Municipios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProvinciaIdChanging(string value);
    partial void OnProvinciaIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRegionChanging(string value);
    partial void OnRegionChanged();
    partial void OnenlaceChanging(string value);
    partial void OnenlaceChanged();
    #endregion
		
		public Provincia()
		{
			this._Municipios = new EntitySet<Municipio>(new Action<Municipio>(this.attach_Municipios), new Action<Municipio>(this.detach_Municipios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinciaId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProvinciaId
		{
			get
			{
				return this._ProvinciaId;
			}
			set
			{
				if ((this._ProvinciaId != value))
				{
					this.OnProvinciaIdChanging(value);
					this.SendPropertyChanging();
					this._ProvinciaId = value;
					this.SendPropertyChanged("ProvinciaId");
					this.OnProvinciaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="VarChar(50)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enlace", DbType="Char(4)")]
		public string enlace
		{
			get
			{
				return this._enlace;
			}
			set
			{
				if ((this._enlace != value))
				{
					this.OnenlaceChanging(value);
					this.SendPropertyChanging();
					this._enlace = value;
					this.SendPropertyChanged("enlace");
					this.OnenlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_Municipio", Storage="_Municipios", ThisKey="ProvinciaId", OtherKey="ProvinciaId")]
		public EntitySet<Municipio> Municipios
		{
			get
			{
				return this._Municipios;
			}
			set
			{
				this._Municipios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Municipios(Municipio entity)
		{
			this.SendPropertyChanging();
			entity.Provincia = this;
		}
		
		private void detach_Municipios(Municipio entity)
		{
			this.SendPropertyChanging();
			entity.Provincia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Municipio")]
	public partial class Municipio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MunicipioId;
		
		private string _ProvinciaId;
		
		private string _Nombre;
		
		private int _Id;
		
		private string _Nombre2;
		
		private EntitySet<DistritoMunicipal> _DistritoMunicipals;
		
		private EntityRef<Provincia> _Provincia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMunicipioIdChanging(string value);
    partial void OnMunicipioIdChanged();
    partial void OnProvinciaIdChanging(string value);
    partial void OnProvinciaIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombre2Changing(string value);
    partial void OnNombre2Changed();
    #endregion
		
		public Municipio()
		{
			this._DistritoMunicipals = new EntitySet<DistritoMunicipal>(new Action<DistritoMunicipal>(this.attach_DistritoMunicipals), new Action<DistritoMunicipal>(this.detach_DistritoMunicipals));
			this._Provincia = default(EntityRef<Provincia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MunicipioId
		{
			get
			{
				return this._MunicipioId;
			}
			set
			{
				if ((this._MunicipioId != value))
				{
					this.OnMunicipioIdChanging(value);
					this.SendPropertyChanging();
					this._MunicipioId = value;
					this.SendPropertyChanged("MunicipioId");
					this.OnMunicipioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinciaId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProvinciaId
		{
			get
			{
				return this._ProvinciaId;
			}
			set
			{
				if ((this._ProvinciaId != value))
				{
					if (this._Provincia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProvinciaIdChanging(value);
					this.SendPropertyChanging();
					this._ProvinciaId = value;
					this.SendPropertyChanged("ProvinciaId");
					this.OnProvinciaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre2", DbType="Char(100)")]
		public string Nombre2
		{
			get
			{
				return this._Nombre2;
			}
			set
			{
				if ((this._Nombre2 != value))
				{
					this.OnNombre2Changing(value);
					this.SendPropertyChanging();
					this._Nombre2 = value;
					this.SendPropertyChanged("Nombre2");
					this.OnNombre2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Municipio_DistritoMunicipal", Storage="_DistritoMunicipals", ThisKey="ProvinciaId,MunicipioId", OtherKey="ProvinciaId,MunicipioId")]
		public EntitySet<DistritoMunicipal> DistritoMunicipals
		{
			get
			{
				return this._DistritoMunicipals;
			}
			set
			{
				this._DistritoMunicipals.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_Municipio", Storage="_Provincia", ThisKey="ProvinciaId", OtherKey="ProvinciaId", IsForeignKey=true)]
		public Provincia Provincia
		{
			get
			{
				return this._Provincia.Entity;
			}
			set
			{
				Provincia previousValue = this._Provincia.Entity;
				if (((previousValue != value) 
							|| (this._Provincia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provincia.Entity = null;
						previousValue.Municipios.Remove(this);
					}
					this._Provincia.Entity = value;
					if ((value != null))
					{
						value.Municipios.Add(this);
						this._ProvinciaId = value.ProvinciaId;
					}
					else
					{
						this._ProvinciaId = default(string);
					}
					this.SendPropertyChanged("Provincia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DistritoMunicipals(DistritoMunicipal entity)
		{
			this.SendPropertyChanging();
			entity.Municipio = this;
		}
		
		private void detach_DistritoMunicipals(DistritoMunicipal entity)
		{
			this.SendPropertyChanging();
			entity.Municipio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DistritoMunicipal")]
	public partial class DistritoMunicipal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DistritoMunicipalId;
		
		private string _ProvinciaId;
		
		private string _MunicipioId;
		
		private string _Nombre;
		
		private int _Id;
		
		private EntitySet<Seccion> _Seccions;
		
		private EntityRef<Municipio> _Municipio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDistritoMunicipalIdChanging(string value);
    partial void OnDistritoMunicipalIdChanged();
    partial void OnProvinciaIdChanging(string value);
    partial void OnProvinciaIdChanged();
    partial void OnMunicipioIdChanging(string value);
    partial void OnMunicipioIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    #endregion
		
		public DistritoMunicipal()
		{
			this._Seccions = new EntitySet<Seccion>(new Action<Seccion>(this.attach_Seccions), new Action<Seccion>(this.detach_Seccions));
			this._Municipio = default(EntityRef<Municipio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistritoMunicipalId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DistritoMunicipalId
		{
			get
			{
				return this._DistritoMunicipalId;
			}
			set
			{
				if ((this._DistritoMunicipalId != value))
				{
					this.OnDistritoMunicipalIdChanging(value);
					this.SendPropertyChanging();
					this._DistritoMunicipalId = value;
					this.SendPropertyChanged("DistritoMunicipalId");
					this.OnDistritoMunicipalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinciaId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProvinciaId
		{
			get
			{
				return this._ProvinciaId;
			}
			set
			{
				if ((this._ProvinciaId != value))
				{
					if (this._Municipio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProvinciaIdChanging(value);
					this.SendPropertyChanging();
					this._ProvinciaId = value;
					this.SendPropertyChanged("ProvinciaId");
					this.OnProvinciaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MunicipioId
		{
			get
			{
				return this._MunicipioId;
			}
			set
			{
				if ((this._MunicipioId != value))
				{
					if (this._Municipio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMunicipioIdChanging(value);
					this.SendPropertyChanging();
					this._MunicipioId = value;
					this.SendPropertyChanged("MunicipioId");
					this.OnMunicipioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DistritoMunicipal_Seccion", Storage="_Seccions", ThisKey="DistritoMunicipalId,ProvinciaId,MunicipioId", OtherKey="DistritoMunicipalId,ProvinciaId,MunicipioId")]
		public EntitySet<Seccion> Seccions
		{
			get
			{
				return this._Seccions;
			}
			set
			{
				this._Seccions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Municipio_DistritoMunicipal", Storage="_Municipio", ThisKey="ProvinciaId,MunicipioId", OtherKey="ProvinciaId,MunicipioId", IsForeignKey=true)]
		public Municipio Municipio
		{
			get
			{
				return this._Municipio.Entity;
			}
			set
			{
				Municipio previousValue = this._Municipio.Entity;
				if (((previousValue != value) 
							|| (this._Municipio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Municipio.Entity = null;
						previousValue.DistritoMunicipals.Remove(this);
					}
					this._Municipio.Entity = value;
					if ((value != null))
					{
						value.DistritoMunicipals.Add(this);
						this._ProvinciaId = value.ProvinciaId;
						this._MunicipioId = value.MunicipioId;
					}
					else
					{
						this._ProvinciaId = default(string);
						this._MunicipioId = default(string);
					}
					this.SendPropertyChanged("Municipio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Seccions(Seccion entity)
		{
			this.SendPropertyChanging();
			entity.DistritoMunicipal = this;
		}
		
		private void detach_Seccions(Seccion entity)
		{
			this.SendPropertyChanging();
			entity.DistritoMunicipal = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seccion")]
	public partial class Seccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SeccionId;
		
		private string _ProvinciaId;
		
		private string _MunicipioId;
		
		private string _DistritoMunicipalId;
		
		private string _Nombre;
		
		private int _Id;
		
		private EntitySet<Barrio> _Barrios;
		
		private EntityRef<DistritoMunicipal> _DistritoMunicipal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSeccionIdChanging(string value);
    partial void OnSeccionIdChanged();
    partial void OnProvinciaIdChanging(string value);
    partial void OnProvinciaIdChanged();
    partial void OnMunicipioIdChanging(string value);
    partial void OnMunicipioIdChanged();
    partial void OnDistritoMunicipalIdChanging(string value);
    partial void OnDistritoMunicipalIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    #endregion
		
		public Seccion()
		{
			this._Barrios = new EntitySet<Barrio>(new Action<Barrio>(this.attach_Barrios), new Action<Barrio>(this.detach_Barrios));
			this._DistritoMunicipal = default(EntityRef<DistritoMunicipal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeccionId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SeccionId
		{
			get
			{
				return this._SeccionId;
			}
			set
			{
				if ((this._SeccionId != value))
				{
					this.OnSeccionIdChanging(value);
					this.SendPropertyChanging();
					this._SeccionId = value;
					this.SendPropertyChanged("SeccionId");
					this.OnSeccionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinciaId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProvinciaId
		{
			get
			{
				return this._ProvinciaId;
			}
			set
			{
				if ((this._ProvinciaId != value))
				{
					if (this._DistritoMunicipal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProvinciaIdChanging(value);
					this.SendPropertyChanging();
					this._ProvinciaId = value;
					this.SendPropertyChanged("ProvinciaId");
					this.OnProvinciaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MunicipioId
		{
			get
			{
				return this._MunicipioId;
			}
			set
			{
				if ((this._MunicipioId != value))
				{
					if (this._DistritoMunicipal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMunicipioIdChanging(value);
					this.SendPropertyChanging();
					this._MunicipioId = value;
					this.SendPropertyChanged("MunicipioId");
					this.OnMunicipioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistritoMunicipalId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DistritoMunicipalId
		{
			get
			{
				return this._DistritoMunicipalId;
			}
			set
			{
				if ((this._DistritoMunicipalId != value))
				{
					if (this._DistritoMunicipal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDistritoMunicipalIdChanging(value);
					this.SendPropertyChanging();
					this._DistritoMunicipalId = value;
					this.SendPropertyChanged("DistritoMunicipalId");
					this.OnDistritoMunicipalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seccion_Barrio", Storage="_Barrios", ThisKey="SeccionId,ProvinciaId,MunicipioId,DistritoMunicipalId", OtherKey="SeccionId,ProvinciaId,MunicipioId,DistritoMunicipalId")]
		public EntitySet<Barrio> Barrios
		{
			get
			{
				return this._Barrios;
			}
			set
			{
				this._Barrios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DistritoMunicipal_Seccion", Storage="_DistritoMunicipal", ThisKey="DistritoMunicipalId,ProvinciaId,MunicipioId", OtherKey="DistritoMunicipalId,ProvinciaId,MunicipioId", IsForeignKey=true)]
		public DistritoMunicipal DistritoMunicipal
		{
			get
			{
				return this._DistritoMunicipal.Entity;
			}
			set
			{
				DistritoMunicipal previousValue = this._DistritoMunicipal.Entity;
				if (((previousValue != value) 
							|| (this._DistritoMunicipal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DistritoMunicipal.Entity = null;
						previousValue.Seccions.Remove(this);
					}
					this._DistritoMunicipal.Entity = value;
					if ((value != null))
					{
						value.Seccions.Add(this);
						this._DistritoMunicipalId = value.DistritoMunicipalId;
						this._ProvinciaId = value.ProvinciaId;
						this._MunicipioId = value.MunicipioId;
					}
					else
					{
						this._DistritoMunicipalId = default(string);
						this._ProvinciaId = default(string);
						this._MunicipioId = default(string);
					}
					this.SendPropertyChanged("DistritoMunicipal");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Barrios(Barrio entity)
		{
			this.SendPropertyChanging();
			entity.Seccion = this;
		}
		
		private void detach_Barrios(Barrio entity)
		{
			this.SendPropertyChanging();
			entity.Seccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Barrio")]
	public partial class Barrio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ProvinciaId;
		
		private string _MunicipioId;
		
		private string _DistritoMunicipalId;
		
		private string _SeccionId;
		
		private string _BarrioId;
		
		private string _Nombre;
		
		private int _Id;
		
		private System.Nullable<int> _circ;
		
		private System.Nullable<double> _longitud;
		
		private System.Nullable<double> _latitud;
		
		private EntitySet<SubBarrio> _SubBarrios;
		
		private EntityRef<Seccion> _Seccion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProvinciaIdChanging(string value);
    partial void OnProvinciaIdChanged();
    partial void OnMunicipioIdChanging(string value);
    partial void OnMunicipioIdChanged();
    partial void OnDistritoMunicipalIdChanging(string value);
    partial void OnDistritoMunicipalIdChanged();
    partial void OnSeccionIdChanging(string value);
    partial void OnSeccionIdChanged();
    partial void OnBarrioIdChanging(string value);
    partial void OnBarrioIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OncircChanging(System.Nullable<int> value);
    partial void OncircChanged();
    partial void OnlongitudChanging(System.Nullable<double> value);
    partial void OnlongitudChanged();
    partial void OnlatitudChanging(System.Nullable<double> value);
    partial void OnlatitudChanged();
    #endregion
		
		public Barrio()
		{
			this._SubBarrios = new EntitySet<SubBarrio>(new Action<SubBarrio>(this.attach_SubBarrios), new Action<SubBarrio>(this.detach_SubBarrios));
			this._Seccion = default(EntityRef<Seccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinciaId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProvinciaId
		{
			get
			{
				return this._ProvinciaId;
			}
			set
			{
				if ((this._ProvinciaId != value))
				{
					if (this._Seccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProvinciaIdChanging(value);
					this.SendPropertyChanging();
					this._ProvinciaId = value;
					this.SendPropertyChanged("ProvinciaId");
					this.OnProvinciaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MunicipioId
		{
			get
			{
				return this._MunicipioId;
			}
			set
			{
				if ((this._MunicipioId != value))
				{
					if (this._Seccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMunicipioIdChanging(value);
					this.SendPropertyChanging();
					this._MunicipioId = value;
					this.SendPropertyChanged("MunicipioId");
					this.OnMunicipioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistritoMunicipalId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DistritoMunicipalId
		{
			get
			{
				return this._DistritoMunicipalId;
			}
			set
			{
				if ((this._DistritoMunicipalId != value))
				{
					if (this._Seccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDistritoMunicipalIdChanging(value);
					this.SendPropertyChanging();
					this._DistritoMunicipalId = value;
					this.SendPropertyChanged("DistritoMunicipalId");
					this.OnDistritoMunicipalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeccionId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SeccionId
		{
			get
			{
				return this._SeccionId;
			}
			set
			{
				if ((this._SeccionId != value))
				{
					if (this._Seccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSeccionIdChanging(value);
					this.SendPropertyChanging();
					this._SeccionId = value;
					this.SendPropertyChanged("SeccionId");
					this.OnSeccionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarrioId", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BarrioId
		{
			get
			{
				return this._BarrioId;
			}
			set
			{
				if ((this._BarrioId != value))
				{
					this.OnBarrioIdChanging(value);
					this.SendPropertyChanging();
					this._BarrioId = value;
					this.SendPropertyChanged("BarrioId");
					this.OnBarrioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_circ", DbType="Int")]
		public System.Nullable<int> circ
		{
			get
			{
				return this._circ;
			}
			set
			{
				if ((this._circ != value))
				{
					this.OncircChanging(value);
					this.SendPropertyChanging();
					this._circ = value;
					this.SendPropertyChanged("circ");
					this.OncircChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitud", DbType="Float")]
		public System.Nullable<double> longitud
		{
			get
			{
				return this._longitud;
			}
			set
			{
				if ((this._longitud != value))
				{
					this.OnlongitudChanging(value);
					this.SendPropertyChanging();
					this._longitud = value;
					this.SendPropertyChanged("longitud");
					this.OnlongitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitud", DbType="Float")]
		public System.Nullable<double> latitud
		{
			get
			{
				return this._latitud;
			}
			set
			{
				if ((this._latitud != value))
				{
					this.OnlatitudChanging(value);
					this.SendPropertyChanging();
					this._latitud = value;
					this.SendPropertyChanged("latitud");
					this.OnlatitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Barrio_SubBarrio", Storage="_SubBarrios", ThisKey="BarrioId,ProvinciaId,MunicipioId,DistritoMunicipalId,SeccionId", OtherKey="BarrioId,ProvinciaId,MunicipioId,DistritoMunicipalId,SeccionId")]
		public EntitySet<SubBarrio> SubBarrios
		{
			get
			{
				return this._SubBarrios;
			}
			set
			{
				this._SubBarrios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seccion_Barrio", Storage="_Seccion", ThisKey="SeccionId,ProvinciaId,MunicipioId,DistritoMunicipalId", OtherKey="SeccionId,ProvinciaId,MunicipioId,DistritoMunicipalId", IsForeignKey=true)]
		public Seccion Seccion
		{
			get
			{
				return this._Seccion.Entity;
			}
			set
			{
				Seccion previousValue = this._Seccion.Entity;
				if (((previousValue != value) 
							|| (this._Seccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seccion.Entity = null;
						previousValue.Barrios.Remove(this);
					}
					this._Seccion.Entity = value;
					if ((value != null))
					{
						value.Barrios.Add(this);
						this._SeccionId = value.SeccionId;
						this._ProvinciaId = value.ProvinciaId;
						this._MunicipioId = value.MunicipioId;
						this._DistritoMunicipalId = value.DistritoMunicipalId;
					}
					else
					{
						this._SeccionId = default(string);
						this._ProvinciaId = default(string);
						this._MunicipioId = default(string);
						this._DistritoMunicipalId = default(string);
					}
					this.SendPropertyChanged("Seccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SubBarrios(SubBarrio entity)
		{
			this.SendPropertyChanging();
			entity.Barrio = this;
		}
		
		private void detach_SubBarrios(SubBarrio entity)
		{
			this.SendPropertyChanging();
			entity.Barrio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubBarrio")]
	public partial class SubBarrio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ProvinciaId;
		
		private string _MunicipioId;
		
		private string _DistritoMunicipalId;
		
		private string _SeccionId;
		
		private string _BarrioId;
		
		private string _SubBarrioId;
		
		private string _Nombre;
		
		private EntityRef<Barrio> _Barrio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProvinciaIdChanging(string value);
    partial void OnProvinciaIdChanged();
    partial void OnMunicipioIdChanging(string value);
    partial void OnMunicipioIdChanged();
    partial void OnDistritoMunicipalIdChanging(string value);
    partial void OnDistritoMunicipalIdChanged();
    partial void OnSeccionIdChanging(string value);
    partial void OnSeccionIdChanged();
    partial void OnBarrioIdChanging(string value);
    partial void OnBarrioIdChanged();
    partial void OnSubBarrioIdChanging(string value);
    partial void OnSubBarrioIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public SubBarrio()
		{
			this._Barrio = default(EntityRef<Barrio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinciaId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProvinciaId
		{
			get
			{
				return this._ProvinciaId;
			}
			set
			{
				if ((this._ProvinciaId != value))
				{
					if (this._Barrio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProvinciaIdChanging(value);
					this.SendPropertyChanging();
					this._ProvinciaId = value;
					this.SendPropertyChanged("ProvinciaId");
					this.OnProvinciaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MunicipioId
		{
			get
			{
				return this._MunicipioId;
			}
			set
			{
				if ((this._MunicipioId != value))
				{
					if (this._Barrio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMunicipioIdChanging(value);
					this.SendPropertyChanging();
					this._MunicipioId = value;
					this.SendPropertyChanged("MunicipioId");
					this.OnMunicipioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistritoMunicipalId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DistritoMunicipalId
		{
			get
			{
				return this._DistritoMunicipalId;
			}
			set
			{
				if ((this._DistritoMunicipalId != value))
				{
					if (this._Barrio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDistritoMunicipalIdChanging(value);
					this.SendPropertyChanging();
					this._DistritoMunicipalId = value;
					this.SendPropertyChanged("DistritoMunicipalId");
					this.OnDistritoMunicipalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeccionId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SeccionId
		{
			get
			{
				return this._SeccionId;
			}
			set
			{
				if ((this._SeccionId != value))
				{
					if (this._Barrio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSeccionIdChanging(value);
					this.SendPropertyChanging();
					this._SeccionId = value;
					this.SendPropertyChanged("SeccionId");
					this.OnSeccionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarrioId", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BarrioId
		{
			get
			{
				return this._BarrioId;
			}
			set
			{
				if ((this._BarrioId != value))
				{
					if (this._Barrio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBarrioIdChanging(value);
					this.SendPropertyChanging();
					this._BarrioId = value;
					this.SendPropertyChanged("BarrioId");
					this.OnBarrioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubBarrioId", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SubBarrioId
		{
			get
			{
				return this._SubBarrioId;
			}
			set
			{
				if ((this._SubBarrioId != value))
				{
					this.OnSubBarrioIdChanging(value);
					this.SendPropertyChanging();
					this._SubBarrioId = value;
					this.SendPropertyChanged("SubBarrioId");
					this.OnSubBarrioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Barrio_SubBarrio", Storage="_Barrio", ThisKey="BarrioId,ProvinciaId,MunicipioId,DistritoMunicipalId,SeccionId", OtherKey="BarrioId,ProvinciaId,MunicipioId,DistritoMunicipalId,SeccionId", IsForeignKey=true)]
		public Barrio Barrio
		{
			get
			{
				return this._Barrio.Entity;
			}
			set
			{
				Barrio previousValue = this._Barrio.Entity;
				if (((previousValue != value) 
							|| (this._Barrio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Barrio.Entity = null;
						previousValue.SubBarrios.Remove(this);
					}
					this._Barrio.Entity = value;
					if ((value != null))
					{
						value.SubBarrios.Add(this);
						this._BarrioId = value.BarrioId;
						this._ProvinciaId = value.ProvinciaId;
						this._MunicipioId = value.MunicipioId;
						this._DistritoMunicipalId = value.DistritoMunicipalId;
						this._SeccionId = value.SeccionId;
					}
					else
					{
						this._BarrioId = default(string);
						this._ProvinciaId = default(string);
						this._MunicipioId = default(string);
						this._DistritoMunicipalId = default(string);
						this._SeccionId = default(string);
					}
					this.SendPropertyChanged("Barrio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
